### ISSUE TITLE
建议wiki里的git clone后面的地址换成https://github.com/Qihoo360/mysql-sniffer

### ISSUE THREAD

**Issue by leafonsword** [Qihoo360/mysql-sniffer#18]
用git@github这种方式会失败：
`root@xxxx:/tmp>git clone git@github.com:Qihoo360/mysql-sniffer.git
Initialized empty Git repository in /tmp/mysql-sniffer/.git/
The authenticity of host 'github.com (192.30.255.112)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
`

而换成[https://github.com/Qihoo360/mysql-sniffer](https://github.com/Qihoo360/mysql-sniffer)就没关系
`
root@xxxx:/tmp>git clone https://github.com/Qihoo360/mysql-sniffer
Initialized empty Git repository in /tmp/mysql-sniffer/.git/
remote: Counting objects: 236, done.
remote: Total 236 (delta 0), reused 0 (delta 0), pack-reused 236
Receiving objects: 100% (236/236), 262.06 KiB | 227 KiB/s, done.
Resolving deltas: 100% (100/100), done.`

**Comment by nathan6** [comment]
多谢，已经修改
