### ISSUE TITLE
编译出现错误

### ISSUE THREAD

**Issue by long904** [Qihoo360/mysql-sniffer#4]
建立proj目录进行编译时，出现「cp: cannot create regular file `../../lib/libnidstcpreasm.a': No such file or directory」错误。尝试很多方法，最终还是出现以下错误
Linking CXX executable mysql-sniffer
/usr/bin/ld: cannot find -lnidstcpreasm

**Comment by nathan6** [comment]
问题已经解决，重新获取源码试试
