### ISSUE TITLE
cmake 编译报错

### ISSUE THREAD

**Issue by Thy0108** [Qihoo360/mysql-sniffer#5]
killtcp.c:59:20: error: libnet.h: No such file or directory
killtcp.c:60: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘tcp_tag’
killtcp.c:62: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
killtcp.c: In function ‘raw_init’:
killtcp.c:66: error: ‘l’ undeclared (first use in this function)
killtcp.c:66: error: (Each undeclared identifier is reported only once
killtcp.c:66: error: for each function it appears in.)
killtcp.c:66: error: ‘LIBNET_RAW4’ undeclared (first use in this function)
killtcp.c: In function ‘nids_killtcp_seq’:
killtcp.c:79: error: ‘l’ undeclared (first use in this function)
killtcp.c:81: error: ‘tcp_tag’ undeclared (first use in this function)
killtcp.c:85: error: ‘LIBNET_TCP_H’ undeclared (first use in this function)
killtcp.c:86: error: ‘ip_tag’ undeclared (first use in this function)
killtcp.c:87: error: ‘LIBNET_IPV4_H’ undeclared (first use in this function)
make: *** [killtcp.o] Error 1

**Comment by yihaoDeng** [comment]
有几个依赖的， 看看readme

**Comment by xiaobenxiong** [comment]
[root@iZ288zn7gymZ proj]# make
Linking CXX executable mysql-sniffer
/usr/bin/ld: cannot find -lnidstcpreasm
collect2: error: ld returned 1 exit status
make[2]: *** [bin/mysql-sniffer] Error 1
make[1]: *** [bin/CMakeFiles/mysql-sniffer.dir/all] Error 2
make: *** [all] Error 2

===============================
请问这是什么原因，依赖也装了

**Comment by yihaoDeng** [comment]
拉一下最新的源码，再试试

**Comment by vectorzjl** [comment]
在项目主目录下执行mkdir lib,新建lib空目录，然后再在proj目录下执行cmake ../，然后在proj目录下执行make就可以编译过了，这是源码的bug

**Comment by nathan6** [comment]
昨天已经解决了，拉最新的源码已经有 lib 目录了

**Comment by vectorzjl** [comment]
@nathan6 想请问一下参数-f怎么使用

**Comment by nathan6** [comment]
@vectorzjl  -f 参数是用来分析用 tcpdump 抓取的数据包，指定数据包文件路径即可分析出对应的 sql
