### ISSUE TITLE
CentOS release 6.7 (Final) configure make error 

### ISSUE THREAD

**Issue by busyfree** [Qihoo360/mysql-sniffer#7]
[mysql-sniffer/proj]$make 
Scanning dependencies of target mysql-sniffer
[ 16%] Building C object bin/CMakeFiles/mysql-sniffer.dir/main.c.o
[ 33%] Building C object bin/CMakeFiles/mysql-sniffer.dir/mysql-dissector.c.o
/mysql-sniffer/src/mysql-dissector.c: In function ‘decode_mysql_lenenc_int’:
/mysql-sniffer/src/mysql-dissector.c:112:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     return *(int*)value;
     ^
[ 50%] Building C object bin/CMakeFiles/mysql-sniffer.dir/util.c.o
[ 66%] Building CXX object bin/CMakeFiles/mysql-sniffer.dir/session.cpp.o
[ 83%] Building CXX object bin/CMakeFiles/mysql-sniffer.dir/sniff-config.cpp.o
/mysql-sniffer/src/sniff-config.cpp: In function ‘int parse_cmdline_option(int, char**)’:
/mysql-sniffer/src/sniff-config.cpp:183:9: warning: variable ‘opt_len’ set but not used [-Wunused-but-set-variable]
     int opt_len;
         ^
[100%] Building CXX object bin/CMakeFiles/mysql-sniffer.dir/sniff-log.cpp.o
Linking CXX executable mysql-sniffer
[100%] Built target mysql-sniffer

**Comment by latelan** [comment]
这只是些waring，我编译也有，不过可以用啊

**Comment by busyfree** [comment]
make 之后没有生存bin 目录文件

**Comment by busyfree** [comment]
发现问题了，看错误目录了
